// <auto-generated />
namespace QC.MF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fanyao20190920 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fanyao20190920));
        
        string IMigrationMetadata.Id
        {
            get { return "201909200838495_fanyao20190920"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
