// <auto-generated />
namespace QC.MF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class yanwei20199121630 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(yanwei20199121630));
        
        string IMigrationMetadata.Id
        {
            get { return "201909120830251_yanwei20199121630"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
