// <auto-generated />
namespace QC.MF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fanyao2019092001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fanyao2019092001));
        
        string IMigrationMetadata.Id
        {
            get { return "201909200931529_fanyao2019092001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
